/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/pages/**/*.{js,jsx,ts,tsx}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          light: '#4F46E5',
          dark: '#6366F1',
        }
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-background',
    'text-foreground',
    'bg-gray-50',
    'dark:bg-gray-900',
    'bg-white',
    'dark:bg-gray-800',
    'text-gray-900',
    'dark:text-white',
    'text-gray-500',
    'dark:text-gray-400',
    'border-gray-300',
    'dark:border-gray-600',
    'bg-gray-200',
    'dark:bg-gray-700',
    'bg-blue-600',
    'dark:bg-blue-500',
    'bg-green-600',
    'dark:bg-green-500',
    'bg-red-600',
    'dark:bg-red-500',
    'bg-yellow-600',
    'dark:bg-yellow-500',
    'bg-purple-600',
    'dark:bg-purple-500',
    'bg-indigo-600',
    'dark:bg-indigo-500',
    'text-blue-600',
    'dark:text-blue-400',
    'text-green-600',
    'dark:text-green-400',
    'text-red-600',
    'dark:text-red-400',
    'text-yellow-600',
    'dark:text-yellow-400',
    'text-purple-600',
    'dark:text-purple-400',
    'text-indigo-600',
    'dark:text-indigo-400',
    'bg-blue-100',
    'dark:bg-blue-900/30',
    'bg-green-100',
    'dark:bg-green-900/30',
    'bg-red-100',
    'dark:bg-red-900/30',
    'bg-yellow-100',
    'dark:bg-yellow-900/30',
    'bg-purple-100',
    'dark:bg-purple-900/30',
    'bg-indigo-100',
    'dark:bg-indigo-900/30',
    'text-blue-100',
    'dark:text-blue-200',
    'text-green-100',
    'dark:text-green-200',
    'text-red-100',
    'dark:text-red-200',
    'text-yellow-100',
    'dark:text-yellow-200',
    'text-purple-100',
    'dark:text-purple-200',
    'text-indigo-100',
    'dark:text-indigo-200',
  ]
}