/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/pages/**/*.{js,jsx,ts,tsx}",
    "./src/App.jsx",
    "./src/main.jsx"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        border: 'hsl(var(--border))',
        primary: {
          light: '#4F46E5',
          dark: '#6366F1',
        }
      },
    },
  },
  plugins: [],
  safelist: [
    // Custom colors
    'bg-background',
    'text-foreground',
    'border-border',
    'dark:bg-background',
    'dark:text-foreground',
    'dark:border-border',
    
    // Layout
    'container',
    'mx-auto',
    'px-4',
    'py-8',
    'min-h-screen',
    'max-w-7xl',
    'w-full',
    'h-full',
    'flex',
    'grid',
    'hidden',
    'block',
    'inline-block',
    'inline-flex',
    'items-center',
    'justify-center',
    'justify-between',
    'space-x-4',
    'space-y-4',
    'gap-4',
    'divide-y',
    'divide-x',
    
    // Spacing
    'p-4',
    'px-4',
    'py-4',
    'm-4',
    'mx-4',
    'my-4',
    'mt-4',
    'mb-4',
    'ml-4',
    'mr-4',
    
    // Colors
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-500',
    'bg-gray-600',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    'bg-blue-600',
    'bg-green-600',
    'bg-red-600',
    'bg-yellow-600',
    'bg-purple-600',
    'bg-indigo-600',
    'bg-orange-600',
    
    // Dark mode colors
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-gray-700',
    'dark:bg-gray-600',
    'dark:bg-gray-500',
    'dark:bg-gray-400',
    'dark:bg-gray-300',
    'dark:bg-gray-200',
    'dark:bg-gray-100',
    'dark:bg-white',
    'dark:bg-blue-500',
    'dark:bg-green-500',
    'dark:bg-red-500',
    'dark:bg-yellow-500',
    'dark:bg-purple-500',
    'dark:bg-indigo-500',
    'dark:bg-orange-500',
    
    // Text colors
    'text-white',
    'text-gray-50',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'text-blue-600',
    'text-green-600',
    'text-red-600',
    'text-yellow-600',
    'text-purple-600',
    'text-indigo-600',
    'text-orange-600',
    
    // Dark mode text colors
    'dark:text-white',
    'dark:text-gray-50',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:text-gray-400',
    'dark:text-gray-500',
    'dark:text-gray-600',
    'dark:text-gray-700',
    'dark:text-gray-800',
    'dark:text-gray-900',
    'dark:text-blue-500',
    'dark:text-green-500',
    'dark:text-red-500',
    'dark:text-yellow-500',
    'dark:text-purple-500',
    'dark:text-indigo-500',
    'dark:text-orange-500',
    
    // Borders
    'border',
    'border-gray-200',
    'border-gray-300',
    'border-gray-400',
    'border-gray-500',
    'border-gray-600',
    'border-gray-700',
    'border-gray-800',
    'border-gray-900',
    'border-blue-600',
    'border-green-600',
    'border-red-600',
    'border-yellow-600',
    'border-purple-600',
    'border-indigo-600',
    'border-orange-600',
    
    // Dark mode borders
    'dark:border-gray-700',
    'dark:border-gray-600',
    'dark:border-gray-500',
    'dark:border-gray-400',
    'dark:border-gray-300',
    'dark:border-gray-200',
    'dark:border-gray-100',
    'dark:border-white',
    'dark:border-blue-500',
    'dark:border-green-500',
    'dark:border-red-500',
    'dark:border-yellow-500',
    'dark:border-purple-500',
    'dark:border-indigo-500',
    'dark:border-orange-500',
    
    // Typography
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-light',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    
    // Effects
    'shadow',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'rounded',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-full',
    
    // Transitions
    'transition',
    'transition-colors',
    'transition-opacity',
    'transition-transform',
    'duration-150',
    'duration-200',
    'duration-300',
    
    // Interactive states
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-gray-200',
    'hover:bg-gray-300',
    'hover:bg-gray-400',
    'hover:bg-gray-500',
    'hover:bg-gray-600',
    'hover:bg-gray-700',
    'hover:bg-gray-800',
    'hover:bg-gray-900',
    'hover:text-white',
    'hover:text-gray-50',
    'hover:text-gray-100',
    'hover:text-gray-200',
    'hover:text-gray-300',
    'hover:text-gray-400',
    'hover:text-gray-500',
    'hover:text-gray-600',
    'hover:text-gray-700',
    'hover:text-gray-800',
    'hover:text-gray-900',
    
    // Dark mode hover states
    'dark:hover:bg-gray-800',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-600',
    'dark:hover:bg-gray-500',
    'dark:hover:bg-gray-400',
    'dark:hover:bg-gray-300',
    'dark:hover:bg-gray-200',
    'dark:hover:bg-gray-100',
    'dark:hover:bg-white',
    'dark:hover:text-white',
    'dark:hover:text-gray-50',
    'dark:hover:text-gray-100',
    'dark:hover:text-gray-200',
    'dark:hover:text-gray-300',
    'dark:hover:text-gray-400',
    'dark:hover:text-gray-500',
    'dark:hover:text-gray-600',
    'dark:hover:text-gray-700',
    'dark:hover:text-gray-800',
    'dark:hover:text-gray-900',
  ]
}